### ISSUE TITLE
BUG: ulmo fails to install with HDF 1.10

### ISSUE THREAD

**Issue by jhamman** [ulmo-dev/ulmo#135]
I'm getting this error when installing via pip or directly from source:

```
Running tables-3.3.0/setup.py -q bdist_egg --dist-dir /var/folders/xg/6ytzsn_91vx7h87q3_k8njtc0000gn/T/easy_install-9f3k4rpu/tables-3.3.0/egg-dist-tmp-i0cup9w4
* Using Python 3.4.5 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:47:57) 
* USE_PKGCONFIG: True
.. ERROR:: HDF5 1.10 release not supported. HDF5 v1.8 release required. Found version v1.10.0
error: Setup script exited with 1
```

**Comment by dharhas** [comment]
pip install is not recommended. It looks like you are using anaconda. We have packaged ulmo for anaconda. To install use the conda-forge community channel, I.e:

conda install -c conda-forge ulmo

**Comment by jhamman** [comment]
I may have misread the original error.  Is v1.10 not supported (only v1.8)?

**Comment by dharhas** [comment]
The error is in the installation of pytables which is an optional dependency of ulmo. Installing all the Scientific Python libraries that ulmo depends on is difficult to do correct with pip. That's why we recommend using the conda install method instead. Anaconda/conda already has all the Scientific packages packaged correctly for various platforms and versions.

If you really want to pip install, you will need to raise this on the pytables site.

**Comment by jhamman** [comment]
Okay, thanks. 

I'm quite familiar with conda-forge.
