### ISSUE TITLE
Add default wsdl_url for CUAHSI WOF endpoint

### ISSUE THREAD

**Issue by dshean** [ulmo-dev/ulmo#202]
At present, the user specifies the wsdl_url: https://ulmo.readthedocs.io/en/latest/api.html?highlight=snotel#module-ulmo.cuahsi.wof
Seems like we could include latest endpoint by default, and allow the user to override if desired.  Latest url (as of late August 2021): https://hydroportal.cuahsi.org/Snotel/cuahsi_1_1.asmx?WSDL

**Comment by emiliom** [comment]
@dshean I'm not sure I follow what you're suggesting. The latest url you listed is only for the snotel endpoint that's part of the CUAHSI HIS Central service, but the cuahsi wof reader is not tied to any specific service. The CUAHSI HIS Central service alone hosts [99 different endpoints](https://hiscentral.cuahsi.org/), and snotel is only one of those. So, there's no default possible for the ulmo cuahsi wof reader.

Now, a higher-level functionality could be to build on the fact that the CUAHSI HIS Central service is the most widely used wof service, and develop a convenient shorthand for CUAHSI so instead of having to pass the endpoint url  to `wsdl_url`, a user could pass a string like "CUAHSI:Snotel" where the presence of the CUAHSI token would result in the string being handled like this:

```python
wsdl_url = "CUAHSI:Snotel"

if ":" in wsdl_url and wsdl_url.split(':')[0].lower() == "cuahsi":
    wsdl_url = "https://hydroportal.cuahsi.org/{}/cuahsi_1_1.asmx?WSDL".format(wsdl_url.split(':')[1])
```

The user would still need to know the correct data service endpoint code from CUAHSI HIS Central (eg, Snotel), but at least it would provide some convenience and a central place to update the CUAHSI WOF domain and service url template.

Is that what you had in mind?

**Comment by dshean** [comment]
All makes sense.  The truth is I hadn't thought about it very much :) 
Probably simplest to just let the user specify the latest url for their desired endpoint.

**Comment by emiliom** [comment]
> Probably simplest to just let the user specify the latest url for their desired endpoint.

That's definitely the simplest, since it entails no changes :wink:
