### ISSUE TITLE
Make an ulmo conda package that works on Wakari

### ISSUE THREAD

**Issue by rsignell-usgs** [ulmo-dev/ulmo#75]
It would be nice to have an ulmo conda package that worked on Wakari so that folks would just do "conda install ulmo".

**Comment by dharhas** [comment]
@rsignell-usgs @wilsaj 

I think I've got this working and it should be cross platform because the hard dependencies (pytables etc) are already in conda and all the others are pure python. details here: https://github.com/ulmo-dev/conda-recipes.

Anyway to install: 

    conda install -c ulmo ulmo

I've tested this on osx, win-32 and wakari (which according to uname is linux-64) and it seems to be working fine. If you have access to win-64, linux-32 please try installing.

I will tweak the documentation to mention this install option and do a pull request soon.

**Comment by dharhas** [comment]
ulmo is packaged in the ioos channel now.

  conda install -c ioos ulmo
